application:
  port: 8007
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
