application:
  port: 8007
  host: 0.0.0.0
  hmac_secret: "long-and-very-secret-random-key-used-for-message-integrity"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  name: "newsletter"
  require_ssl: false
email_client:
  base_url: "http://localhost"
  token: "token_value"
  timeout_milliseconds: 10000
