application:
  port: 8007
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  name: "newsletter"
  require_ssl: false
email_client:
  base_url: "http://localhost"
  token: "token_value"
